// <auto-generated />
namespace Hitter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chatcontext5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chatcontext5));
        
        string IMigrationMetadata.Id
        {
            get { return "202103241305086_chatcontext5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
