// <auto-generated />
namespace Hitter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chatcontext4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chatcontext4));
        
        string IMigrationMetadata.Id
        {
            get { return "202103241303384_chatcontext4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
